title: EasyTask Frontend
theme: minima
exclude:
  - node_modules
  - frontend
  - build
  - public
  - src
  - README.md
  - package.json
  - package-lock.json
  - frontend.zip
sass:
  sass_dir: assets/css
plugins:
  - jekyll-feed
markdown: kramdown
